apiVersion: v1
kind: Service
metadata:
  name: {{phoqer.app_name}}
spec:
  selector:
    app: {{phoqer.app_name}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{phoqer.port}}
  type: NodePort

