apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.app_name}}
spec:
  selector:
    app: {{cookiecutter.app_name}}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: {{cookiecutter.port}}
  type: NodePort

